name: Build Extensions

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Extension for Chrome and Firefox
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extensions
        run: pnpm build

      - name: Create builds directory
        run: mkdir -p builds

      - name: Zip Chrome extension
        run: cd dist && zip -r ../builds/chrome.zip chrome

      - name: Zip Firefox extension
        run: cd dist && zip -r ../builds/firefox.zip firefox

      - name: Add builds to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: builds/*.zip
